### ISSUE TITLE
minified HTML is blank

### ISSUE THREAD

**Issue by TPurple** [geekpradd/sublime-html5-minifier#2]
I'm on a macbook running 10.10 yosemite. I'm using Sublime Text build 3065. The HTML5 minifier seems to work perfectly for CSS, but my minified HTML files are always blank. I've tried removing and reinstalling the package and closing and reopening Sublime, but to no effect. I also deleted the .min.html file that was blank, and now when I click "minify" it won't even create the file for me.
I appreciate you working on this.

**Comment by geekpradd** [comment]
@tlferrin , The major problem is the fact that I don't have a Macbook.. I tested and developed this plugin on Windows, and then switched to Ubuntu. There were many problems on OS X as seen in an earlier Issue. 

So, would you kindly test the plugin out for me? I'll try fixing the problem and I'll let you know when I've solved the problem.

Thanks for the feedback,

**Comment by geekpradd** [comment]
Also can you post a screenshot of the Python Console that has the traceback of the error (I think the shortcut is Cmd+` )

**Comment by geekpradd** [comment]
@tlferrin , Everything is working fine in Linux and Windows, Please post the traceback otherwise my hands are tied (I need to see the error to work on it)

**Comment by TPurple** [comment]
I'm not super tech-savvy, but I opened the console and here is what it said:

Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "Minfier in /Users/thomasferrin/Library/Application Support/Sublime
Text 3/Installed Packages/HTML Minifier.sublime-package", line 38, in main
  File "Minfier in /Users/thomasferrin/Library/Application Support/Sublime
Text 3/Installed Packages/HTML Minifier.sublime-package", line 26, in
locationParams
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by geekpradd** [comment]
I think I solved your problem in Version 1.3.

The problem was in this line:

``` python
self.name = self.location.split('\\')[-1]
```

For OS X and Linux, the code should be

``` python
self.name = self.location.split('/')[-1]
```

The reason is that paths are different for Unix based systems and Windows. Since I developed the plugin on Windows first, that part was overlooked.

Try installing the Plugin again and then please leave a reply stating whether the new version works for you or not. Till then, I'm leaving the Issue open.

**Comment by TPurple** [comment]
I uninstalled and reinstalled the plugin. When I ran it, it created a blank
.min.html file, and the console said:

Exception in thread Thread-23:

> Traceback (most recent call last):
>   File "./threading.py", line 901, in _bootstrap_inner
>   File "./threading.py", line 858, in run
>   File "Minfier in /Users/thomasferrin/Library/Application Support/Sublime
> Text 3/Installed Packages/HTML Minifier.sublime-package", line 50, in
> writeMinified
> UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in
> position 601: ordinal not in range(128)
> no command for selector: noop:
> no command for selector: noop:

So I deleted the .min.html file, re-ran the minifier, and it didn't create
a new file. Now the console says:

Traceback (most recent call last):

>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py",
> line 547, in run_
>     edit = self.view.begin_edit(edit_token, self.name())
> TypeError: 'str' object is not callable

Thanks again for working on this.

**Comment by geekpradd** [comment]
The second error is a Sublime Plugin constraint. I've been trying to fix it but apparently the problem is in the sublime plugins file which I can't solve.

@FicheteFoll, any suggestions?

The first is a Unicode error. Looks like I'm switching modules. I'll let you know tomorrow.

**Comment by TPurple** [comment]
Update: I used Minify (modify current) instead of (create new) and it
worked perfectly.

**Comment by TPurple** [comment]
Well, almost perfectly. I still get this in the console:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py",
line 554, in run_
    edit = self.view.begin_edit(edit_token, self.name())
TypeError: 'str' object is not callable

**Comment by martingarcia1981** [comment]
Hi, great plugin! Unfortunately I think this is still not solved.

This is the console output I got when trying to minify an html file...

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 572, in run_
    edit = self.view.begin_edit(edit_token, self.name())
TypeError: 'str' object is not callable
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'clear' is not defined
Exception in thread Thread-79:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "Minfier in /Users/martin/Library/Application Support/Sublime Text 3/Installed Packages/HTML Minifier.sublime-package", line 68, in write_minified
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1516: ordinal not in range(128)

I don't know anything about python, but I found this on stackoverflow... http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

Hopefully it helps.
